### ISSUE TITLE
Can't get RFC3339 to format pre-defined "time"

### ISSUE THREAD

**Issue by Rendez** [samber/slog-formatter#17]
According to the docs, to get UTC  with RFC3339 (ending in `z`) it's enough to do this:

```go
logger = slog.New(slogformatter.NewFormatterHandler(
			slogformatter.TimezoneConverter(time.UTC),
			slogformatter.TimeFormatter(time.DateTime, nil),
		)(
			slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{
				ReplaceAttr: func(groups []string, a slog.Attr) slog.Attr {
					if a.Key == "time" {
						return slog.Attr{Key: "timestamp", Value: a.Value}
					}
					return a
				},
			}),
		),
		)
```

> Note that I want `timestamp` instead of the default `time` (for consistency with other services).

But I am still getting my local ISO date (Berlin):

```json
{"timestamp":"2024-12-15T13:30:08.24871+01:00","level":"INFO","msg":"Starting app router..."}
```

Thanks in advanced,

**Comment by samber** [comment]
`time` is not an attribute but a simple data added by the `JSONHandler`.

When the error message and attributes go through your formatters, the `time` attribute does not exist yet.

Feel free to suggest a change to the documentation!

**Comment by Rendez** [comment]
How could I change the time attribute format then?

**Comment by samber** [comment]
Make your own json handler?
