### ISSUE TITLE
Is there a plan for slog-gorm?

### ISSUE THREAD

**Issue by rts-gordon** [samber/slog-formatter#3]
HI @samber 

  Thanks for your awesome work for slog, is there a plan for slog-gorm? You know, [gorm](https://github.com/go-gorm/gorm) is an famouse ORM framework, it will be wonderful if there is a slog adapter for it.

  Thank you.

**Comment by samber** [comment]
hi @rts-gordon,

I made no plan for such handler because we cannot predict the attribute the developer wants to inject into dedicated columns vs catch-all jsonb column.

If you have any idea on that point, I suppose we can push it forward.

**Comment by rts-gordon** [comment]
Hi @samber 
  
 Maybe we don't have to think about columns, just think about logs for gorm. 
 There is another repo about [slog-gorm](https://github.com/orandin/slog-gorm) for reference.

**Comment by samber** [comment]
Oh! I see. I was thinking about a handler for pushing logs to a SQL database.

What would be the value compared to [slog-gorm](https://github.com/orandin/slog-gorm) ?

**Comment by rts-gordon** [comment]
yes, [slog-gorm](https://github.com/orandin/slog-gorm) is good enough. 

Just thought it would be better that all slog adapter come from one source. haha :)
