### ISSUE TITLE
 How to format time for simple output

### ISSUE THREAD

**Issue by wpecker** [samber/slog-formatter#5]
How to format and print as follows: 
```
09-24 08:03:57 DEBUG msg="Info message"
09-24 08:03:58 INFO  msg="Info message"
09-24 08:03:59 ERROR msg="Info message"
```

thanks

**Comment by wpecker** [comment]
as: https://stackoverflow.com/questions/77422213/how-to-hide-all-keys-when-using-slog-in-golang

**Comment by samber** [comment]
You can use slog.TextHandler from the stdlib or https://github.com/lmittmann/tint
